version: "3"
services:
  www-dangxproject:
    container_name: dangx-www-dangxproject
    image: nginx
    expose:
      - "80"
    ports:
      - "3000:80"
    environment:
      - VIRTUAL_HOST=dangxproject.dev
    volumes:
      - ./www-dangxproject:/usr/share/nginx/html
networks:
  default:
    external:
      name: nginx-proxy