version: "3"
services:
    www-api:
        container_name: dangx-www-api
        image: dangx/nodejs
        build: .
        expose:
            - "80"
        ports:
            - "3001:80"
        environment:
            VIRTUAL_HOST: api.dangxproject.dev
